"""Country list for the search form, plus LinkedIn geo id hints.

``COUNTRIES`` is the ISO 3166-1 set of country names. The Streamlit selectbox
renders them sorted alphabetically and is type-to-search, so the user can jump
straight to "Netherlands" without scrolling.

``GEO_IDS`` maps a handful of countries to LinkedIn's internal ``geoId``. Those
ids make the search noticeably more accurate, but LinkedIn does not publish
them, so the map is deliberately partial and best-effort: any country without
an entry simply falls back to sending the country name as free-text location,
which LinkedIn resolves itself. The UI always shows which geo id (if any) was
used and lets you override it.
"""

from __future__ import annotations

ANYWHERE = "Anywhere (no country filter)"

COUNTRIES: tuple[str, ...] = (
    "Afghanistan",
    "Albania",
    "Algeria",
    "Andorra",
    "Angola",
    "Antigua and Barbuda",
    "Argentina",
    "Armenia",
    "Australia",
    "Austria",
    "Azerbaijan",
    "Bahamas",
    "Bahrain",
    "Bangladesh",
    "Barbados",
    "Belarus",
    "Belgium",
    "Belize",
    "Benin",
    "Bhutan",
    "Bolivia",
    "Bosnia and Herzegovina",
    "Botswana",
    "Brazil",
    "Brunei",
    "Bulgaria",
    "Burkina Faso",
    "Burundi",
    "Cambodia",
    "Cameroon",
    "Canada",
    "Cape Verde",
    "Central African Republic",
    "Chad",
    "Chile",
    "China",
    "Colombia",
    "Comoros",
    "Congo",
    "Costa Rica",
    "Croatia",
    "Cuba",
    "Cyprus",
    "Czechia",
    "Democratic Republic of the Congo",
    "Denmark",
    "Djibouti",
    "Dominica",
    "Dominican Republic",
    "Ecuador",
    "Egypt",
    "El Salvador",
    "Equatorial Guinea",
    "Eritrea",
    "Estonia",
    "Eswatini",
    "Ethiopia",
    "Fiji",
    "Finland",
    "France",
    "Gabon",
    "Gambia",
    "Georgia",
    "Germany",
    "Ghana",
    "Greece",
    "Grenada",
    "Guatemala",
    "Guinea",
    "Guinea-Bissau",
    "Guyana",
    "Haiti",
    "Honduras",
    "Hong Kong",
    "Hungary",
    "Iceland",
    "India",
    "Indonesia",
    "Iran",
    "Iraq",
    "Ireland",
    "Israel",
    "Italy",
    "Ivory Coast",
    "Jamaica",
    "Japan",
    "Jordan",
    "Kazakhstan",
    "Kenya",
    "Kiribati",
    "Kuwait",
    "Kyrgyzstan",
    "Laos",
    "Latvia",
    "Lebanon",
    "Lesotho",
    "Liberia",
    "Libya",
    "Liechtenstein",
    "Lithuania",
    "Luxembourg",
    "Macao",
    "Madagascar",
    "Malawi",
    "Malaysia",
    "Maldives",
    "Mali",
    "Malta",
    "Marshall Islands",
    "Mauritania",
    "Mauritius",
    "Mexico",
    "Micronesia",
    "Moldova",
    "Monaco",
    "Mongolia",
    "Montenegro",
    "Morocco",
    "Mozambique",
    "Myanmar",
    "Namibia",
    "Nauru",
    "Nepal",
    "Netherlands",
    "New Zealand",
    "Nicaragua",
    "Niger",
    "Nigeria",
    "North Korea",
    "North Macedonia",
    "Norway",
    "Oman",
    "Pakistan",
    "Palau",
    "Palestine",
    "Panama",
    "Papua New Guinea",
    "Paraguay",
    "Peru",
    "Philippines",
    "Poland",
    "Portugal",
    "Qatar",
    "Romania",
    "Russia",
    "Rwanda",
    "Saint Kitts and Nevis",
    "Saint Lucia",
    "Saint Vincent and the Grenadines",
    "Samoa",
    "San Marino",
    "Sao Tome and Principe",
    "Saudi Arabia",
    "Senegal",
    "Serbia",
    "Seychelles",
    "Sierra Leone",
    "Singapore",
    "Slovakia",
    "Slovenia",
    "Solomon Islands",
    "Somalia",
    "South Africa",
    "South Korea",
    "South Sudan",
    "Spain",
    "Sri Lanka",
    "Sudan",
    "Suriname",
    "Sweden",
    "Switzerland",
    "Syria",
    "Taiwan",
    "Tajikistan",
    "Tanzania",
    "Thailand",
    "Timor-Leste",
    "Togo",
    "Tonga",
    "Trinidad and Tobago",
    "Tunisia",
    "Turkey",
    "Turkmenistan",
    "Tuvalu",
    "Uganda",
    "Ukraine",
    "United Arab Emirates",
    "United Kingdom",
    "United States",
    "Uruguay",
    "Uzbekistan",
    "Vanuatu",
    "Vatican City",
    "Venezuela",
    "Vietnam",
    "Yemen",
    "Zambia",
    "Zimbabwe",
)

# Partial, best-effort map of country -> LinkedIn geoId.
GEO_IDS: dict[str, str] = {
    "Australia": "101452733",
    "Brazil": "106057199",
    "Canada": "101174742",
    "France": "105015875",
    "Germany": "101282230",
    "India": "102713980",
    "Ireland": "104738515",
    "Italy": "103350119",
    "Japan": "101355337",
    "Netherlands": "102890719",
    "Pakistan": "101022442",
    "Poland": "105072130",
    "Saudi Arabia": "100459316",
    "Singapore": "102454443",
    "Spain": "105646813",
    "Sweden": "105117694",
    "Switzerland": "106693272",
    "United Arab Emirates": "104305776",
    "United Kingdom": "101165590",
    "United States": "103644278",
}


def country_options() -> list[str]:
    """Alphabetical country list with the "no filter" sentinel first."""
    return [ANYWHERE, *sorted(COUNTRIES)]


def geo_id_for(country: str) -> str:
    """LinkedIn geoId for ``country``, or "" when we do not have one."""
    return GEO_IDS.get(country, "")


def location_string(country: str, city: str = "") -> str:
    """Build the free-text location LinkedIn should search in."""
    city = (city or "").strip()
    if country == ANYWHERE or not country:
        return city
    if city:
        return f"{city}, {country}"
    return country
